services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: graphcore/pytorch:3.3.0-ubuntu-20.04-20230703
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

